version: '3.9'

networks:
  app_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  mysql_mws_data:

services:
  frontend:
    build: ./app
    container_name: front
    tty: true
    volumes:
      - ./app:/app:cached
    restart: always
    environment:
      - TZ=${TZ}
    command: sh -c "cd my-work-space && yarn start"
    ports:
      - "3001:3000"
    networks:
      - app_network
    depends_on:
        - backend

  backend:
    build: ./backend
    container_name: back
    tty: true
    volumes:
      - ./backend:/backend
    restart: always
    environment:
      - TZ=${TZ}
    command: sh -c "node index.js"
    working_dir: "/backend"
    ports:
      - 3002:3000
    networks:
      - app_network
      - backend_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - ./db/logs:/var/log/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - mysql_mws_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=${DB_ROOT_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - '3306:3306'
    networks:
      - backend_network